#!/usr/bin/env perl
use strict;
use warnings;


my $firstNum = 0;
my $secondNum = 0;
for (my $i = 0; $i <=100;$i++){
	$firstNum = ($i*$i) + $firstNum;
}
for (my $i = 0; $i <=100;$i++){
	$secondNum = $i + $secondNum;
	#print("$secondNum\n");
}

my $thirdNum = $secondNum * $secondNum;
print($thirdNum - $firstNum);
