#!/usr/bin/perl

use strict;
use warnings;

my $tri = 0;
$|=1;
#for (my $i = 1;$i < 1000000000;$i++){
	
	#$tri = $i + $tri;
	#print("$tri\n");
	my $x = 200;
	my %fact;
	my $fact = 2;
	do {
	++$fact while $x/$fact*$fact != $x;
	++$fact{$fact};
	$x /= $fact;
	} while ($x > 1);

	# apply all combinations
	my @fact = 1;
	#print("@fact\n");
	while (($fact,my $count) = each %fact) {
	my $index;
	@fact = map $_ * $fact**(++$index/@fact % ($count+1)),
		    (@fact) x ($count+1);
	}
	# if (@fact == 10){
		# print("The Number is $tri\n");
		# # for my $planet (@fact) {
			# # print $planet . "\n";
		# # }
		# #print("$fact\n");
		# last;
	# }
	print "@{[sort {$a<=>$b} @fact]}\n";


# }
