#!/usr/bin/env perl
use strict;
use warnings;

my @fibilist = ();
sub fibi {
        my ($text) = @_;
	print $text;
	my $answer = <STDIN>;
        chomp $answer;
        # my $number = shift;
        my $curnum = 1;
        my $prvnum = 0;
        my $sum;
        # if ($number ==1 || $number ==2){
                # return 1;
        # }
        # $number -= 2;
        while($curnum < $answer){
		$sum = $curnum + $prvnum;
		print("$sum\n");
		if ($sum%2 == 0){
			push @fibilist, $sum;
		}
		$prvnum = $curnum;
		$curnum = $sum;
	}
	my $theSum = 0;
        foreach my $num(@fibilist){
                $theSum = $theSum + $num;
        }
        print("The sum is $theSum\n");
}

my $test2 = fibi("Enter a number you want to find sum of the even fibi numbers under : ");
