#!/usr/bin/perl
use strict;
use warnings;
use bignum;



my $testVar = 102030405060708090;
# print($testVar);
# print $testVar % 100, "\n";


sub secondCheck{
	my ($check) = @_;
	#print($check);
	if (substr($check,0,1)== "1" && substr($check,2,1)=="2" && substr($check,4,1)=="3" && substr($check,6,1)=="4" && substr($check,8,1)=="5" && substr($check,10,1)=="6" && substr($check,12,1)=="7" && substr($check,14,1)=="8" && substr($check,16,1)=="9"){
		return 1;
	}
	else {
		return 0;
	}
	return 0;
}
print (secondCheck($testVar));



# if (int($testVar) == $testVar){
	# print("Same\n");
# }
# else {
	# print("Not the Same\n");
# }
