#!/usr/bin/perl
my $start_run = time();

use strict;
use warnings;

use bignum;
use List::Util 'sum';

sub factorial {
	my ($number) = @_;
	#print $number;
	my $final = 1;
	for (my $i = 1; $i<=$number; $i++)
	{
		$final *= $i;
		#print("$final\n");
	}
	#print $final;
	my @splited = split //, $final;
	#print (@splited);
	my $superSum = sum(@splited);
	print ("The answer is : $superSum\n");
}

print(factorial(100));
my $end_run = time();
my $run_time = $end_run - $start_run;
print "Job took $run_time seconds\n";
